//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportBill
    {
        public int ImpID { get; set; }
        public Nullable<int> ImpDate { get; set; }
        public Nullable<int> PrvID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> TotalPay { get; set; }
    
        public virtual ImportBillDetail ImportBillDetail { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
    }
}
