//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_3_v3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdID { get; set; }
        public Nullable<int> CusID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string DeliveryAddress { get; set; }
        public string Status { get; set; }
        public double TotalPay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
